SET @configuration_group_id=0;

SELECT (@configuration_group_id:=configuration_group_id) FROM configuration_group WHERE configuration_group_title= 'Autoresponder+' LIMIT 1;

DELETE FROM configuration WHERE configuration_group_id = @configuration_group_id;
DELETE FROM configuration_group WHERE configuration_group_id = @configuration_group_id;

INSERT INTO configuration_group (configuration_group_id, configuration_group_title, configuration_group_description, sort_order, visible) VALUES (NULL, 'Autoresponder+', 'Autoresponder+ Configuration', '1', '1');
SET @configuration_group_id=last_insert_id();
UPDATE configuration_group SET sort_order = @configuration_group_id WHERE configuration_group_id = @configuration_group_id;

INSERT INTO configuration (configuration_id, configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added, use_function, set_function) VALUES 

(NULL, 'Enable Autoresponder', 'AUTO_ENABLE_AUTORESPONDER', 'false', '<br />Enable Autoresponder', @configuration_group_id, 1, NOW(), NULL, 'zen_cfg_select_option(array(''true'', ''false''), '),

(NULL, 'Enable Preset (1)', 'AUTO_ENABLE_PRESET', 'false', '<br />Enable email preset #1', @configuration_group_id, 2, NOW(), NULL, 'zen_cfg_select_option(array(''true'', ''false''), '),
(NULL, 'Mode (1)', 'AUTO_MODE', 'test', '<br />Set mode <p />When in test mode, emails will be sent to store owner instead', @configuration_group_id, 3, NOW(), NULL, 'zen_cfg_select_option(array(''test'', ''live''), '),
(NULL, 'Query (1)', 'AUTO_STATE', 'order', '<br />Set query <p />Choose <b>order</b> for post-order emailing <p />Choose <b>account</b> for emailing all account creating customers<p />Choose <b>account-no-order</b> for emailing customers who have created an account but never ordered', @configuration_group_id, 4, NOW(), NULL, 'zen_cfg_select_option(array(''order'', ''account'', ''account-no-order''), '),
(NULL, 'Order Status ID (1)', 'AUTO_ORDER_STATUS_ID', '3', '<br />Emails only send for orders with the following status:<p />(ignore if in <b>account</b> state)<br />', @configuration_group_id, 5, NOW(), NULL, NULL),
(NULL, 'Post Order Status ID (1)', 'AUTO_POST_ORDER_STATUS_ID', '3', '<br />Afterwards, change order status to:<p />(If ID is the same as above, no change will be made)<p />(ignore if in <b>account</b> state)<br />', @configuration_group_id, 6, NOW(), NULL, NULL),
(NULL, 'Days After (1)', 'AUTO_DAYS_AFTER', '21', '<br />Amount of days before email is sent', @configuration_group_id, 7, NOW(), NULL, NULL),
(NULL, 'Subscribed (1)', 'AUTO_SUBSCRIBED', 'true', '<br />Must be subscribed to newsletter', @configuration_group_id, 8, NOW(), NULL, 'zen_cfg_select_option(array(''true'', ''false''), '),
(NULL, 'Restrict Location (1)', 'AUTO_LOCATION_RESTRICT', 'no', '<br />Emails are restricted', @configuration_group_id, 9, NOW(), NULL, 'zen_cfg_select_option(array(''no'', ''to zone'', ''to country'', ''from zone'', ''from country''), '),
(NULL, 'Location to Restrict (1)', 'AUTO_LOCATION', 'Kent', '<br />Enter location to restrict to/from<p />(ignore if no restriction)<br />', @configuration_group_id, 10, NOW(), NULL, NULL),
(NULL, 'Subject (1)', 'AUTO_SUBJECT', 'Order Review', 'Enter email subject', @configuration_group_id, 11, NOW(), NULL, NULL),
(NULL, 'Include Customer Name (1)', 'AUTO_INCLUDE_NAME', '0', '<br />Display customer name at beginning of email<p />0 No<br />1 John<br />2 John Smith<br />3 Hi John<br />4 Hi John Smith<br />5 Hello John<br />6 Hello John Smith<br />7 John,<br />8 John Smith,<br />9 Hi John,<br />10 Hi John Smith,<br />11 Hello John,<br />12 Hello John Smith,<br />13 Dear John<br />14 Dear John Smith<br />15 Dear John,<br />16 Dear John Smith,', @configuration_group_id, 12, NOW(), NULL, 'zen_cfg_select_option(array(''0'', ''1'', ''2'', ''3'', ''4'', ''5'', ''6'', ''7'', ''8'', ''9'', ''10'', ''11'', ''12'', ''13'', ''14'', ''15'', ''16''), '),
(NULL, 'Include Product Details (1)', 'AUTO_INCLUDE_PRODUCT_DETAILS', 'true', '<br />Include details of items ordered<p />(ignore if in <b>account</b> state)<br />', @configuration_group_id, 13, NOW(), NULL, 'zen_cfg_select_option(array(''true'', ''false''), '),
(NULL, 'Product Details as Links (1)', 'AUTO_PRODUCT_URL', 'no', '<br />Product details as clickable links<p />(feature experimental - test thoroughly)<br />', @configuration_group_id, 14, NOW(), NULL, 'zen_cfg_select_option(array(''no'', ''yes, to product page'', ''yes, to product review page''), '),
(NULL, 'Restrict Product (1)', 'AUTO_PRODUCT_RESTRICT', '', '<br />Only send email when at least one of the following product IDs are ordered<p />E.g. 1, 2, 3<p />Otherwise leave blank<p />(ignore if in <b>account</b> state)<br />', @configuration_group_id, 15, NOW(), NULL, NULL),
(NULL, 'Include Discount Coupon (1)', 'AUTO_COUPON', '', '<br />Enter existing coupon code to replicate settings from<p />Otherwise leave blank<br />', @configuration_group_id, 16, NOW(), NULL, NULL),
(NULL, 'Pre Text Message (1)', 'AUTO_MESSAGE_TEXT_PRE', 'Enter email here..', '<br />Enter main message<p />Appears <b>before</b> product details<p />Carriage return sensitive<p />Type [coupon] to include an autogenerated new coupon code<br />', @configuration_group_id, 17, NOW(), NULL, 'zen_cfg_textarea('),
(NULL, 'Post Text Message (1)', 'AUTO_MESSAGE_TEXT_POST', 'Enter email here..', '<br />Enter main message<p />Appears <b>after</b> product details<p />Carriage return sensitive<br />', @configuration_group_id, 18, NOW(), NULL, 'zen_cfg_textarea('),
(NULL, 'Pre HTML Message (1)', 'AUTO_MESSAGE_HTML_PRE', 'Enter email here..', '<br />Enter main message<p />Appears <b>before</b> product details<p />HTML allowed<p />Type [coupon] to include an autogenerated new coupon code<br />', @configuration_group_id, 19, NOW(), NULL, 'zen_cfg_textarea('),
(NULL, 'Post HTML Message (1)', 'AUTO_MESSAGE_HTML_POST', 'Enter email here..', '<br />Enter main message<p />Appears <b>after</b> product details<p />HTML allowed<br />', @configuration_group_id, 20, NOW(), NULL, 'zen_cfg_textarea('),

(NULL, 'Enable Preset (2)', 'AUTO_ENABLE_PRESET_2', 'false', '<br />Enable email preset #2', @configuration_group_id, 21, NOW(), NULL, 'zen_cfg_select_option(array(''true'', ''false''), '),
(NULL, 'Mode (2)', 'AUTO_MODE_2', 'test', '<br />Set mode <p />When in test mode, emails will be sent to store owner instead', @configuration_group_id, 22, NOW(), NULL, 'zen_cfg_select_option(array(''test'', ''live''), '),
(NULL, 'Query (2)', 'AUTO_STATE_2', 'order', '<br />Set query <p />Choose <b>order</b> for post-order emailing <p />Choose <b>account</b> for emailing all account creating customers<p />Choose <b>account-no-order</b> for emailing customers who have created an account but never ordered', @configuration_group_id, 23, NOW(), NULL, 'zen_cfg_select_option(array(''order'', ''account'', ''account-no-order''), '),
(NULL, 'Order Status ID (2)', 'AUTO_ORDER_STATUS_ID_2', '3', '<br />Emails only send for orders with the following status:<p />(ignore if in <b>account</b> state)<br />', @configuration_group_id, 24, NOW(), NULL, NULL),
(NULL, 'Post Order Status ID (2)', 'AUTO_POST_ORDER_STATUS_ID_2', '3', '<br />Afterwards, change order status to:<p />(If ID is the same as above, no change will be made)<p />(ignore if in <b>account</b> state)<br />', @configuration_group_id, 25, NOW(), NULL, NULL),
(NULL, 'Days After (2)', 'AUTO_DAYS_AFTER_2', '21', '<br />Amount of days before email is sent', @configuration_group_id, 26, NOW(), NULL, NULL),
(NULL, 'Subscribed (2)', 'AUTO_SUBSCRIBED_2', 'true', '<br />Must be subscribed to newsletter', @configuration_group_id, 27, NOW(), NULL, 'zen_cfg_select_option(array(''true'', ''false''), '),
(NULL, 'Restrict Location (2)', 'AUTO_LOCATION_RESTRICT_2', 'no', '<br />Emails are restricted', @configuration_group_id, 28, NOW(), NULL, 'zen_cfg_select_option(array(''no'', ''to zone'', ''to country'', ''from zone'', ''from country''), '),
(NULL, 'Location to Restrict (2)', 'AUTO_LOCATION_2', 'Canada', '<br />Enter location to restrict to/from<p />(ignore if no restriction)<br />', @configuration_group_id, 29, NOW(), NULL, NULL),
(NULL, 'Subject (2)', 'AUTO_SUBJECT_2', 'Order Review', 'Enter email subject', @configuration_group_id, 30, NOW(), NULL, NULL),
(NULL, 'Include Customer Name (2)', 'AUTO_INCLUDE_NAME_2', '0', '<br />Display customer name at beginning of email<p />0 No<br />1 John<br />2 John Smith<br />3 Hi John<br />4 Hi John Smith<br />5 Hello John<br />6 Hello John Smith<br />7 John,<br />8 John Smith,<br />9 Hi John,<br />10 Hi John Smith,<br />11 Hello John,<br />12 Hello John Smith,<br />13 Dear John<br />14 Dear John Smith<br />15 Dear John,<br />16 Dear John Smith,', @configuration_group_id, 31, NOW(), NULL, 'zen_cfg_select_option(array(''0'', ''1'', ''2'', ''3'', ''4'', ''5'', ''6'', ''7'', ''8'', ''9'', ''10'', ''11'', ''12'', ''13'', ''14'', ''15'', ''16''), '),
(NULL, 'Include Product Details (2)', 'AUTO_INCLUDE_PRODUCT_DETAILS_2', 'true', '<br />Include details of items ordered<p />(ignore if in <b>account</b> state)<br />', @configuration_group_id, 32, NOW(), NULL, 'zen_cfg_select_option(array(''true'', ''false''), '),
(NULL, 'Product Details as Links (2)', 'AUTO_PRODUCT_URL_2', 'no', '<br />Product details as clickable links<p />(feature experimental - test thoroughly)<br />', @configuration_group_id, 33, NOW(), NULL, 'zen_cfg_select_option(array(''no'', ''yes, to product page'', ''yes, to product review page''), '),
(NULL, 'Restrict Product (2)', 'AUTO_PRODUCT_RESTRICT_2', '', '<br />Only send email when at least one of the following product IDs are ordered<p />E.g. 1, 2, 3<p />Otherwise leave blank<p />(ignore if in <b>account</b> state)<br />', @configuration_group_id, 34, NOW(), NULL, NULL),
(NULL, 'Include Discount Coupon (2)', 'AUTO_COUPON_2', '', '<br />Enter existing coupon code to replicate settings from<p />Otherwise leave blank<br />', @configuration_group_id, 35, NOW(), NULL, NULL),
(NULL, 'Pre Text Message (2)', 'AUTO_MESSAGE_TEXT_PRE_2', 'Enter email here..', '<br />Enter main message<p />Appears <b>before</b> product details<p />Carriage return sensitive<p />Type [coupon] to include an autogenerated new coupon code<br />', @configuration_group_id, 36, NOW(), NULL, 'zen_cfg_textarea('),
(NULL, 'Post Text Message (2)', 'AUTO_MESSAGE_TEXT_POST_2', 'Enter email here..', '<br />Enter main message<p />Appears <b>after</b> product details<p />Carriage return sensitive<br />', @configuration_group_id, 37, NOW(), NULL, 'zen_cfg_textarea('),
(NULL, 'Pre HTML Message (2)', 'AUTO_MESSAGE_HTML_PRE_2', 'Enter email here..', '<br />Enter main message<p />Appears <b>before</b> product details<p />HTML allowed<p />Type [coupon] to include an autogenerated new coupon code<br />', @configuration_group_id, 38, NOW(), NULL, 'zen_cfg_textarea('),
(NULL, 'Post HTML Message (2)', 'AUTO_MESSAGE_HTML_POST_2', 'Enter email here..', '<br />Enter main message<p />Appears <b>after</b> product details<p />HTML allowed<br />', @configuration_group_id, 39, NOW(), NULL, 'zen_cfg_textarea('),

(NULL, 'Enable Preset (3)', 'AUTO_ENABLE_PRESET_3', 'false', '<br />Enable email preset #3', @configuration_group_id, 40, NOW(), NULL, 'zen_cfg_select_option(array(''true'', ''false''), '),
(NULL, 'Mode (3)', 'AUTO_MODE_3', 'test', '<br />Set mode <p />When in test mode, emails will be sent to store owner instead', @configuration_group_id, 41, NOW(), NULL, 'zen_cfg_select_option(array(''test'', ''live''), '),
(NULL, 'Query (3)', 'AUTO_STATE_3', 'order', '<br />Set query <p />Choose <b>order</b> for post-order emailing <p />Choose <b>account</b> for emailing all account creating customers<p />Choose <b>account-no-order</b> for emailing customers who have created an account but never ordered', @configuration_group_id, 42, NOW(), NULL, 'zen_cfg_select_option(array(''order'', ''account'', ''account-no-order''), '),
(NULL, 'Order Status ID (3)', 'AUTO_ORDER_STATUS_ID_3', '3', '<br />Emails only send for orders with the following status:<p />(ignore if in <b>account</b> state)<br />', @configuration_group_id, 43, NOW(), NULL, NULL),
(NULL, 'Post Order Status ID (3)', 'AUTO_POST_ORDER_STATUS_ID_3', '3', '<br />Afterwards, change order status to:<p />(If ID is the same as above, no change will be made)<p />(ignore if in <b>account</b> state)<br />', @configuration_group_id, 44, NOW(), NULL, NULL),
(NULL, 'Days After (3)', 'AUTO_DAYS_AFTER_3', '21', '<br />Amount of days before email is sent', @configuration_group_id, 45, NOW(), NULL, NULL),
(NULL, 'Subscribed (3)', 'AUTO_SUBSCRIBED_3', 'true', '<br />Must be subscribed to newsletter', @configuration_group_id, 46, NOW(), NULL, 'zen_cfg_select_option(array(''true'', ''false''), '),
(NULL, 'Restrict Location (3)', 'AUTO_LOCATION_RESTRICT_3', 'no', '<br />Emails are restricted', @configuration_group_id, 47, NOW(), NULL, 'zen_cfg_select_option(array(''no'', ''to zone'', ''to country'', ''from zone'', ''from country''), '),
(NULL, 'Location to Restrict (3)', 'AUTO_LOCATION_3', 'California', '<br />Enter location to restrict to/from<p />(ignore if no restriction)<br />', @configuration_group_id, 48, NOW(), NULL, NULL),
(NULL, 'Subject (3)', 'AUTO_SUBJECT_3', 'Order Review', 'Enter email subject', @configuration_group_id, 49, NOW(), NULL, NULL),
(NULL, 'Include Customer Name (3)', 'AUTO_INCLUDE_NAME_3', '0', '<br />Display customer name at beginning of email<p />0 No<br />1 John<br />2 John Smith<br />3 Hi John<br />4 Hi John Smith<br />5 Hello John<br />6 Hello John Smith<br />7 John,<br />8 John Smith,<br />9 Hi John,<br />10 Hi John Smith,<br />11 Hello John,<br />12 Hello John Smith,<br />13 Dear John<br />14 Dear John Smith<br />15 Dear John,<br />16 Dear John Smith,', @configuration_group_id, 50, NOW(), NULL, 'zen_cfg_select_option(array(''0'', ''1'', ''2'', ''3'', ''4'', ''5'', ''6'', ''7'', ''8'', ''9'', ''10'', ''11'', ''12'', ''13'', ''14'', ''15'', ''16''), '),
(NULL, 'Include Product Details (3)', 'AUTO_INCLUDE_PRODUCT_DETAILS_3', 'true', '<br />Include details of items ordered<p />(ignore if in <b>account</b> state)<br />', @configuration_group_id, 51, NOW(), NULL, 'zen_cfg_select_option(array(''true'', ''false''), '),
(NULL, 'Product Details as Links (3)', 'AUTO_PRODUCT_URL_3', 'no', '<br />Product details as clickable links<p />(feature experimental - test thoroughly)<br />', @configuration_group_id, 52, NOW(), NULL, 'zen_cfg_select_option(array(''no'', ''yes, to product page'', ''yes, to product review page''), '),
(NULL, 'Restrict Product (3)', 'AUTO_PRODUCT_RESTRICT_3', '', '<br />Only send email when at least one of the following product IDs are ordered<p />E.g. 1, 2, 3<p />Otherwise leave blank<p />(ignore if in <b>account</b> state)<br />', @configuration_group_id, 53, NOW(), NULL, NULL),
(NULL, 'Include Discount Coupon (3)', 'AUTO_COUPON_3', '', '<br />Enter existing coupon code to replicate settings from<p />Otherwise leave blank<br />', @configuration_group_id, 54, NOW(), NULL, NULL),
(NULL, 'Pre Text Message (3)', 'AUTO_MESSAGE_TEXT_PRE_3', 'Enter email here..', '<br />Enter main message<p />Appears <b>before</b> product details<p />Carriage return sensitive<p />Type [coupon] to include an autogenerated new coupon code<br />', @configuration_group_id, 55, NOW(), NULL, 'zen_cfg_textarea('),
(NULL, 'Post Text Message (3)', 'AUTO_MESSAGE_TEXT_POST_3', 'Enter email here..', '<br />Enter main message<p />Appears <b>after</b> product details<p />Carriage return sensitive<br />', @configuration_group_id, 56, NOW(), NULL, 'zen_cfg_textarea('),
(NULL, 'Pre HTML Message (3)', 'AUTO_MESSAGE_HTML_PRE_3', 'Enter email here..', '<br />Enter main message<p />Appears <b>before</b> product details<p />HTML allowed<p />Type [coupon] to include an autogenerated new coupon code<br />', @configuration_group_id, 57, NOW(), NULL, 'zen_cfg_textarea('),
(NULL, 'Post HTML Message (3)', 'AUTO_MESSAGE_HTML_POST_3', 'Enter email here..', '<br />Enter main message<p />Appears <b>after</b> product details<p />HTML allowed<br />', @configuration_group_id, 58, NOW(), NULL, 'zen_cfg_textarea('),

(NULL, 'Time Validation', 'AUTO_TIMER', 'false', '<br />Use time validation', @configuration_group_id, 59, NOW(), NULL, 'zen_cfg_select_option(array(''true'', ''false''), '),
(NULL, 'Start Time', 'AUTO_START_TIME', '12:55:00', '<br />Enter start time<p />(Format: 00:00:00)<br />', @configuration_group_id, 60, NOW(), NULL, NULL),
(NULL, 'End Time', 'AUTO_END_TIME', '13:05:00', '<br />Enter end time<p />(Format: 00:00:00)<br />', @configuration_group_id, 61, NOW(), NULL, NULL),
(NULL, 'Log Emails', 'AUTO_LOG_EMAILS', 'false', '<br />Store a log of autoresponder activity, including sent emails', @configuration_group_id, 62, NOW(), NULL, 'zen_cfg_select_option(array(''true'', ''false''), '),
(NULL, 'Log Directory', 'AUTO_LOG_DIRECTORY', '/home/your_web_username/tmp/', '<br />Directory where log is stored<p />Make sure chosen directory is writeable<br />', @configuration_group_id, 63, NOW(), NULL, NULL),
(NULL, 'Admin Copy', 'AUTO_ADMIN_COPY', 'true', '<br />Receive admin copy of email<p />(Copy only sent in live mode)', @configuration_group_id, 64, NOW(), NULL, 'zen_cfg_select_option(array(''true'', ''false''), '),
(NULL, 'Admin Email Address', 'AUTO_OWNER_EMAIL_ADDRESS', '', '<br />Admin email address<p />Change for testing purposes<p />If left blank, default store owner address is used<br />', @configuration_group_id, 65, NOW(), NULL, NULL);

/*
zencart 1.5 mods
*/
INSERT INTO admin_pages (page_key,language_key,main_page,page_params,menu_key,display_on_menu,sort_order) VALUES ('AutoresponderConfig','BOX_CONFIGURATION_AUTORESPONDER','FILENAME_CONFIGURATION',CONCAT('gID=',@configuration_group_id), 'configuration', 'Y', @configuration_group_id);  
